### PR TITLE
Chapter 1 work

### PR DESCRIPTION
**Pull request by shenjibg**
Here is where we are going to review and keep going with your lessons.

### CODE REVIEW

**Comment by shenjibg** [comment]
# Assignment 9/27/2022
- Tasks to perform
 - Open page 15 and go to the website www.getcodingkids.com
 - Read pages 16-19
 - Type in code on page 21

**Comment by AmongUs-AgentScott** [comment]
am I doing good?

**Comment by shenjibg** [comment]
@AmongUs-AgentScott you are doing excellent.
Good Job

**Comment by AmongUs-AgentScott** [comment]
woooo

**Comment by AmongUs-AgentScott** [comment]
Love you dad

**Comment by AmongUs-AgentScott** [comment]
Did it!

**Comment by AmongUs-AgentScott** [comment]
Done reading it 23-31

**Pull request merged**
